### PR TITLE
Fix attenuation oscillation not stabilising

### PR DESCRIPTION
**Pull request by OCopping**

### CODE REVIEW

**Comment by GDYendell** [comment]
I think this is good but should be squashed to one commit. The docs also need updating to say that singleshot stabilises when it hits 0 attenuation or when it increases - currently it just says when it does not cause any adjustment. Also I don't like the formatting...

**Comment by GDYendell** [comment]
> Is it mainly just the subscribe_endpoints you don't like the formatting of? :sweat_smile:

The whitespace padding on the initialiser list is the most offensive bit for sure. I prefer to have opening brace on the same line rather than the next line, trailing brace on its own line - basically black formatting. I also prefer `*`/`&` to be on the type, not the name, e.g. [here](https://github.com/dls-controls/pmacFilterControl/pull/64/files#diff-7f81319b117c0b9f03b7a037e75144303db8923f52c414702361aa75f78cae86R456).

I can see it has caught some bad formatting, which is good. The problem is whatever formatting you are using here isn't being enforced / automated and when the next person works on the project it won't be maintained, so I don't think it is worthwhile reformatting everything unless there is the tooling to keep it consistent.

**Comment by OCopping** [comment]
@GDYendell so just make the formatting changes and merge?

**Comment by GDYendell** [comment]
I think so. I guess this is what is running on the beamline currently?

**Comment by OCopping** [comment]
> The problem is whatever formatting you are using here isn't being enforced / automated

Apparently it was using the default `C/C++` formatter built in to VSCode

**Comment by OCopping** [comment]
@GDYendell I'll update the docs on a different PR if that's okay? They want this on the beamlne ASAP...

**Pull request merged**
